# Generated by Django 4.2.1 on 2023-06-04 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_u', models.CharField(max_length=100)),
                ('lname_u', models.CharField(max_length=100)),
                ('age_u', models.CharField(choices=[('Child', 'Child'), ('Middle', 'Middle'), ('Old', 'Old')], max_length=100)),
                ('sign_u', models.CharField(choices=[('Vision Impairment', 'Vision Impairment'), ('Blind', 'Blind'), ('Mental health disability', 'Mental health disability'), ('Intellectual disability', 'Intellectual disability'), ('Acquired brain injury', 'Acquired brain injury'), ('Autism spectrum disorder', 'Autism spectrum disorder'), ('Handless', 'Handless'), ('Feetless', 'Feetless'), ('Muscular dystrophy', 'Muscular dystrophy'), ('Cerebral palsy', 'Cerebral palsy'), ('Other', 'Other')], max_length=100)),
                ('details_u', models.TextField()),
                ('address_u', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_l', models.ImageField(blank=True, null=True, upload_to=myapp.models.path_and_rename)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FindPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_f', models.CharField(choices=[('Child', 'Child'), ('Middle', 'Middle'), ('Old', 'Old')], max_length=100)),
                ('sign_f', models.CharField(choices=[('Vision Impairment', 'Vision Impairment'), ('Blind', 'Blind'), ('Mental health disability', 'Mental health disability'), ('Intellectual disability', 'Intellectual disability'), ('Acquired brain injury', 'Acquired brain injury'), ('Autism spectrum disorder', 'Autism spectrum disorder'), ('Handless', 'Handless'), ('Feetless', 'Feetless'), ('Muscular dystrophy', 'Muscular dystrophy'), ('Cerebral palsy', 'Cerebral palsy'), ('Other', 'Other')], max_length=100)),
                ('image_f', models.ImageField(blank=True, null=True, upload_to=myapp.models.rename)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
