# Generated by Django 4.2.1 on 2023-06-09 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[
                 ('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('nid', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LostPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_u', models.CharField(max_length=100)),
                ('lname_u', models.CharField(max_length=100)),
                ('age_u', models.CharField(choices=[
                 ('Child', 'Child'), ('Young', 'Young'), ('Middle', 'Middle'), ('Old', 'Old')], max_length=100)),
                ('sign_u', models.CharField(choices=[('Vision_Impairment', 'Vision_Impairment'), ('Blind', 'Blind'), ('Mental_health_disability', 'Mental_health_disability'), ('Intellectual_disability', 'Intellectual_disability'), ('Acquired_brain_injury', 'Acquired_brain_injury'), (
                    'Autism_spectrum_disorder', 'Autism_spectrum_disorder'), ('Handless', 'Handless'), ('Feetless', 'Feetless'), ('Muscular_dystrophy', 'Muscular_dystrophy'), ('Cerebral_palsy', 'Cerebral_palsy'), ('Other', 'Other')], max_length=100)),
                ('details_u', models.TextField()),
                ('address_u', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('image_l', models.ImageField(blank=True, null=True,
                 upload_to=myapp.models.path_and_rename)),
                ('user', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FindPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('age_f', models.CharField(choices=[
                 ('Child', 'Child'), ('Young', 'Young'), ('Middle', 'Middle'), ('Old', 'Old')], max_length=100)),
                ('sign_f', models.CharField(choices=[('Vision_Impairment', 'Vision_Impairment'), ('Blind', 'Blind'), ('Mental_health_disability', 'Mental_health_disability'), ('Intellectual_disability', 'Intellectual_disability'), ('Acquired_brain_injury', 'Acquired_brain_injury'), (
                    'Autism_spectrum_disorder', 'Autism_spectrum_disorder'), ('Handless', 'Handless'), ('Feetless', 'Feetless'), ('Muscular_dystrophy', 'Muscular_dystrophy'), ('Cerebral_palsy', 'Cerebral_palsy'), ('Other', 'Other')], max_length=100)),
                ('image_f', models.ImageField(blank=True,
                 null=True, upload_to=myapp.models.rename)),
                ('user', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
